import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";

import { ClerkProvider, useUser } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { dark } from "@clerk/themes";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={lexend.className + " flex flex-col min-h-screen"}>
          <header className="max-w p-4">
            <Navbar />
          </header>
          <div className="max-w mx-auto flex  justify-center items-center">
            {children}
          </div>
          <footer className="max-w p-4 mt-auto">
            <Footer />
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
