import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={lexend.className + " flex flex-col min-h-screen"}>
          <header className="max-w p-4">
            <Navbar />
          </header>
          <div className="max-w mx-auto flex-grow">{children}</div>
          <footer className="max-w p-4 mt-auto">
            <p>© {new Date().getFullYear()} Chess Tactics</p>
            <p>GitHub</p>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
